# Generated by Django 4.2.7 on 2025-09-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance_checker', '0002_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
