# Generated by Django 4.2.7 on 2025-09-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_checker', '0003_remove_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rfid_number',
            field=models.CharField(blank=True, help_text='RFID card number for tap ID purposes', max_length=50, null=True, unique=True),
        ),
    ]
