# Generated by Django 4.2.7 on 2025-09-24 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balance_checker', '0004_student_rfid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the balance was last updated'),
        ),
    ]
